# There are 2 automation for adzan; 1 is for Subuh, 2 is for the rest of the prayer time (Zohor, Asar, Maghrib, Isyak)
# Place the adzan audio mp3 files to path /media/audio
# Change the media_player entity id to your device name. 

- id: '01'
  alias: Adzan
  description: ''
  trigger:
  - platform: template
    value_template: '{{state_attr("sensor.esolat_zohor", "24hours") == states("sensor.time")}}'
  - platform: template
    value_template: '{{state_attr("sensor.esolat_asar", "24hours") == states("sensor.time")}}'
  - platform: template
    value_template: '{{state_attr("sensor.esolat_maghrib", "24hours") == states("sensor.time")}}'
  - platform: template
    value_template: '{{state_attr("sensor.esolat_isyak", "24hours") == states("sensor.time")}}'
  condition: []
  action:
  - service: tts.google_say # May varies for Alexa users. Please change accordingly
    data:
      entity_id: media_player.all_devices # Change to your own device name
      message: >-
        Sekarang telah masuk waktu {{ states.sensor.esolat_waktusekarang.state }}
        bagi kawasan ini dan kawasan kawasan yang sama waktu dengannya.
      language: id
  - delay: 00:00:10
  - service: media_player.play_media
    data:
      media_content_type: audio/mp3
      media_content_id: media-source://media_source/local/audio/azan.mp3
      #media_content_id: https://xxxx.duckdns.org/local/audio/azan.mp3 <-- you can also use direct URL if media-source doesnt work.
    entity_id: media_player.all_devices # Change to your own device name
  mode: single

- id: '02'
  alias: Adzan Subuh
  description: ''
  trigger:
  - platform: template
    value_template: '{{state_attr("sensor.esolat_subuh", "24hours") == states("sensor.time")}}'
  condition: []
  action:
  - service: tts.google_say # May varies for Alexa users. Please change accordingly
    data:
      entity_id: media_player.all_devices # Change to your own device name
      message: >- 
        Sekarang telah masuk waktu Subuh bagi kawasan ini dan kawasan kawasan
        yang sama waktu dengannya.
      language: id
  - delay: 00:00:10
  - service: media_player.play_media
    data:
      media_content_type: audio/mp3
      media_content_id: media-source://media_source/local/audio/azansubuh.mp3
      #media_content_id: https://xxxx.duckdns.org/local/audio/azansubuh.mp3 <-- you can also use direct URL if media-source doesnt work.      
    entity_id: media_player.all_devices # Change to your own device name
  mode: single

- id: '03'
  alias: Azan Maghrib Reminder
  description: ''
  trigger:
  - platform: template
    value_template: {{state_attr("sensor.esolat_maghrib", "24hours") == (as_local(now()).strftime("%s") | int + (25*60)) | timestamp_custom("%H:%M", false)}}
    # the number 25 in int + (25*60) represent the minutes. Change it to your desired timing.
  condition: []
  action:
  - service: tts.google_say
    data:
      message: It is 25 minutes before Maghrib! Get prepare.
      entity_id: media_player.all_devices
      language: en
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: media_player.play_media
    data:
      media_content_type: audio/mp3
      media_content_id: media-source://media_source/local/audio/alfatihah.mp3 #Kita mulakan dengan Ummul Kitab
    entity_id: media_player.all_devices
  - delay: #ikut pada timing mp3 alfatihah..
      hours: 0
      minutes: 0
      seconds: 37
      milliseconds: 0
  - service: media_player.play_media
    data:
      media_content_type: audio/mp3
      media_content_id: |
        {{ ["media-source://media_source/local/audio/surah1.mp3",
            "media-source://media_source/local/audio/surah2.mp3",
            "media-source://media_source/local/audio/surah3.mp3",
            "media-source://media_source/local/audio/surah4.mp3",
            ] | random }}
      extra: #bacaan surah pilihan secara random. Gantikan dengan sumber audio mengikut keperluan anda.
        title: Surah Pilihan 
    entity_id: media_player.all_devices
  mode: single
