## This automation adds a takbir after Azan based on conditions that matches Eid Fitr and Eid Adha.
## Adjust the newly added delay accordingly (line 68 and 108) to match the audio (surah) length.

alias: Azan 3.0 (with Takbir)
description: ''
trigger:
  - platform: template
    value_template: >-
      {{is_state_attr("sensor.solat_sekarang", "24hours",
      now().strftime("%H:%M"))}}
condition: []
action:
  - choose:
      - conditions:
          - condition: template
            value_template: '{{is_state("sensor.solat_sekarang", "Subuh")}}'
        sequence:
          - service: notify.telegram #Change this accordingly
            data:
              message: >-
                🕋 Sekarang telah masuk waktu
                {{states("sensor.solat_sekarang")}} bagi kawasan ini dan
                kawasan yang sama waktu dengannya.
          - service: persistent_notification.create
            data:
              message: >-
                {{ now().strftime("%-I:%M %p") }} - Sekarang telah masuk waktu
                {{states("sensor.solat_sekarang")}} bagi kawasan ini dan kawasan yang
                sama waktu dengannya.
              notification_id: esolat_azan
              title: 🕋 eSolat - Waktu {{states("sensor.solat_sekarang")}}
          - service: tts.google_say
            data:
              entity_id: media_player.all_devices #Change this accordingly
              message: >-
                Sekarang telah masuk waktu {{states("sensor.solat_sekarang")}}
                bagi kawasan ini dan kawasan kawasan yang sama waktu dengannya.
              language: id
          - delay: '00:00:10'
          - service: media_player.play_media
            data:
              media_content_type: audio/mp3
              media_content_id: https://xxxx.duckdns.org/local/audio/azan/azansubuh.mp3 #Change this accordingly
              extra:
                title: Azan {{states("sensor.solat_sekarang")}}
            target:
              entity_id: media_player.all_devices #Change this accordingly
          - delay: '00:05:00'
          - service: media_player.play_media
            data:
              media_content_type: audio/mp3
              media_content_id: https://xxxx.duckdns.org/local/audio/surah/alfatihah.mp3 #Change this accordingly
              extra:
                title: Surah Al Fatihah
            entity_id: media_player.all_devices #Change this accordingly
          - delay: '00:00:37'
          - service: media_player.play_media
            data:
              media_content_type: audio/mp3
              media_content_id: >
                {{
                ["https://xxxx.duckdns.org/local/audio/surah/assajadah.mp3",
                 "https://xxxx.duckdns.org/local/audio/surah/almulk.mp3",
                ] | random }}
              extra:
                title: Surah
            entity_id: media_player.all_devices #Change this accordingly
          - delay: '00:06:21'
      - conditions:
          - condition: template
            value_template: >-
              {{is_state("sensor.solat_sekarang", "Zohor") or
              is_state("sensor.solat_sekarang", "Asar") or
              is_state("sensor.solat_sekarang", "Maghrib") or
              is_state("sensor.solat_sekarang", "Isyak")}}
        sequence:
          - service: notify.telegram #Change this accordingly
            data:
              message: >-
                🕋 Sekarang telah masuk waktu
                {{states("sensor.solat_sekarang")}} bagi kawasan ini dan
                kawasan yang sama waktu dengannya.
          - service: persistent_notification.create
            data:
              message: >-
                {{ now().strftime("%-I:%M %p") }} - Sekarang telah masuk waktu
                {{states("sensor.solat_sekarang")}} bagi kawasan ini dan kawasan yang
                sama waktu dengannya.
              notification_id: esolat_azan
              title: 🕋 eSolat - Waktu {{states("sensor.solat_sekarang")}}
          - service: tts.google_say
            data:
              entity_id: media_player.all_devices #Change this accordingly
              message: >-
                Sekarang telah masuk waktu {{states("sensor.solat_sekarang")}}
                bagi kawasan ini dan kawasan kawasan yang sama waktu dengannya.
              language: id
          - delay: '00:00:10'
          - service: media_player.play_media
            data:
              media_content_type: audio/mp3
              media_content_id: https://xxxx.duckdns.org/local/audio/azan/azan.mp3
              #media_content_id: http://192.168.0.123:8123/local/audio/azan/azan.mp3 #Change this accordingly
              extra:
                title: Azan {{states("sensor.solat_sekarang")}}
            target:
              entity_id: media_player.all_devices #Change this accordingly
          - delay: '00:02:46'
    default:
      - service: persistent_notification.create
        data:
          message: >-
            {{ now().strftime("%-I:%M %p") }} - Sekarang telah masuk waktu
            {{states("sensor.solat_sekarang")}} bagi kawasan ini dan kawasan yang
            sama waktu dengannya.
          notification_id: esolat_azan
          title: 🕋 eSolat - Waktu {{states("sensor.solat_sekarang")}}
  - condition: template
    value_template: >-
      {% set tasyrik_end = not is_state('sensor.solat_sekarang', 'Maghrib') and not is_state('sensor.solat_sekarang', 'Isyak') %}
      {% set day = state_attr('sensor.solat_jakim', 'prayerTime')[0].hijri[8:10] %}
      {% set month = state_attr('sensor.solat_jakim', 'prayerTime')[0].hijri[5:7] %}
      {{(month == '12' and day > '08' and day < '14' and (day == '13' and tasyrik_end)) or (month == '09' and day == '30' and not tasyrik_end) }}
  - service: media_player.play_media
    data:
      media_content_type: audio/mp3
      media_content_id: media-source://media_source/local/audio/takbir.mp3
      extra:
        title: >-
          Takbir Raya {{state_attr('sensor.solat_jakim', 'prayerTime')[0].hijri[0:4] ~ 'h'}}
    target:
      entity_id: media_player.all_devices          
mode: single
