alias: Azan 3.0
description: ''
trigger:
  - platform: template
    value_template: >-
      {{is_state_attr("sensor.solat_sekarang", "24hours",
      now().strftime("%H:%M"))}}
condition: []
action:
  - choose:
      - conditions:
          - condition: template
            value_template: '{{is_state("sensor.solat_sekarang", "Subuh")}}'
        sequence:
          - service: notify.telegram #Change this accordingly
            data:
              message: >-
                🕋 Sekarang telah masuk waktu
                {{states("sensor.solat_sekarang")}} bagi kawasan ini dan
                kawasan yang sama waktu dengannya.
          - service: persistent_notification.create
            data:
              message: >-
                {{ now().strftime("%-I:%M %p") }} - Sekarang telah masuk waktu
                {{states("sensor.solat_sekarang")}} bagi kawasan ini dan kawasan yang
                sama waktu dengannya.
              notification_id: esolat_azan
              title: 🕋 eSolat - Waktu {{states("sensor.solat_sekarang")}}
          - service: tts.google_say
            data:
              entity_id: media_player.all_devices #Change this accordingly
              message: >-
                Sekarang telah masuk waktu {{states("sensor.solat_sekarang")}}
                bagi kawasan ini dan kawasan kawasan yang sama waktu dengannya.
              language: id
          - delay: '00:00:10'
          - service: media_player.play_media
            data:
              media_content_type: audio/mp3
              media_content_id: https://xxxx.duckdns.org/local/audio/azan/azansubuh.mp3 #Change this accordingly
              extra:
                title: Azan {{states("sensor.solat_sekarang")}}
            target:
              entity_id: media_player.all_devices #Change this accordingly
          - delay: '00:05:00'
          - service: media_player.play_media
            data:
              media_content_type: audio/mp3
              media_content_id: https://xxxx.duckdns.org/local/audio/surah/alfatihah.mp3 #Change this accordingly
              extra:
                title: Surah Al Fatihah
            entity_id: media_player.all_devices #Change this accordingly
          - delay: '00:00:37'
          - service: media_player.play_media
            data:
              media_content_type: audio/mp3
              media_content_id: >
                {{
                ["https://xxxx.duckdns.org/local/audio/surah/assajadah.mp3",
                 "https://xxxx.duckdns.org/local/audio/surah/almulk.mp3",
                ] | random }}
              extra:
                title: Surah
            entity_id: media_player.all_devices #Change this accordingly
      - conditions:
          - condition: template
            value_template: >-
              {{is_state("sensor.solat_sekarang", "Zohor") or
              is_state("sensor.solat_sekarang", "Asar") or
              is_state("sensor.solat_sekarang", "Maghrib") or
              is_state("sensor.solat_sekarang", "Isyak")}}
        sequence:
          - service: notify.telegram #Change this accordingly
            data:
              message: >-
                🕋 Sekarang telah masuk waktu
                {{states("sensor.solat_sekarang")}} bagi kawasan ini dan
                kawasan yang sama waktu dengannya.
          - service: persistent_notification.create
            data:
              message: >-
                {{ now().strftime("%-I:%M %p") }} - Sekarang telah masuk waktu
                {{states("sensor.solat_sekarang")}} bagi kawasan ini dan kawasan yang
                sama waktu dengannya.
              notification_id: esolat_azan
              title: 🕋 eSolat - Waktu {{states("sensor.solat_sekarang")}}
          - service: tts.google_say
            data:
              entity_id: media_player.all_devices #Change this accordingly
              message: >-
                Sekarang telah masuk waktu {{states("sensor.solat_sekarang")}}
                bagi kawasan ini dan kawasan kawasan yang sama waktu dengannya.
              language: id
          - delay: '00:00:10'
          - service: media_player.play_media
            data:
              media_content_type: audio/mp3
              media_content_id: https://xxxx.duckdns.org/local/audio/azan/azan.mp3
              #media_content_id: http://192.168.0.123:8123/local/audio/azan/azan.mp3 #Change this accordingly
              extra:
                title: Azan {{states("sensor.solat_sekarang")}}
            target:
              entity_id: media_player.all_devices #Change this accordingly
    default:
      - service: persistent_notification.create
        data:
          message: >-
            {{ now().strftime("%-I:%M %p") }} - Sekarang telah masuk waktu
            {{states("sensor.solat_sekarang")}} bagi kawasan ini dan kawasan yang
            sama waktu dengannya.
          notification_id: esolat_azan
          title: 🕋 eSolat - Waktu {{states("sensor.solat_sekarang")}}
mode: single

alias: Azan 3.0 Yearly Update
description: Fetch JSON data from JAKIM on 1st January every year
trigger:
  - platform: time
    at: '00:00:00'
condition:
  - condition: template
    value_template: '{{now().day == 1 and now().month == 1}}'
action:
  - service: downloader.download_file
    data:
      url: >-
        https://www.e-solat.gov.my/index.php?r=esolatApi/takwimsolat&period=year&zone={{states('input_text.solat')}}
      filename: esolat.json
      overwrite: true
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: rest.reload
mode: single

alias: Azan 3.0 - Maghrib Reminder
description: ''
trigger:
  - platform: template
    value_template: >-
      {{ state_attr("sensor.solat_maghrib", "24hours") == (now().strftime("%s")
      | int + (15*60)) | timestamp_custom("%H:%M", false) }}
condition: []
action:
  - service: tts.google_say
    data:
      entity_id: media_player.all_devices #Change this accordingly
      message: It is 15 minutes before Maghrib. Get prepare.
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: media_player.play_media
    target:
      entity_id:
        - media_player.all_devices #Change this accordingly
    data:
      media_content_id: https://xxxx.duckdns.org/local/audio/surah/alfatihah.mp3
  - delay:
      hours: 0
      minutes: 0
      seconds: 37
      milliseconds: 0
  - service: media_player.play_media
    target:
      entity_id:
        - media_player.all_devices #Change this accordingly
    data:
      media_content_id: >-
        https://xxxx.duckdns.org/local/audio/surah/{{ ["almulk.mp3",
        "assajadah.mp3", "arrahman.mp3",] | random }}
mode: single
