## Automation Azan - version 3.0
## This config will add the following:
## 1. Added esolat.yaml as sensor
## 2. Enable Downloader (for downloading data from Jakim).
## 3. Create Input Select (for source selection).
## 4. Create Input Text (for location/state code and Home Assistant URL).
## You may enable the "initial" by removing the comment to set the default value (upon Home Assistant restart).

sensor solat: !include esolat.yaml

homeassistant:
  allowlist_external_dirs:
    - "/tmp"
    - "/config/"
  media_dirs:
    media: "/media"
    
## Downloader ##
downloader:
  download_dir: www
  
## Input Select ##
input_select:
  solat:
    name: Solat
    icon: mdi:star-crescent
    options:
      - Local
      - eSolat
      - AzanPro
    #initial: eSolat

## Input Text ##
input_text:
  solat:
    name: Solat State Code
    icon: mdi:star-crescent
    #initial: "sgr01"
  homeurl:
    name: Home Assistant URL
    icon: mdi:home-assistant
    #initial: "https://xxxx.duckdns.org"
    #initial: "http://192.168.0.123:8123"
