# Malaysia prayer time based on JAKIM Official API
# Change the location code based on this list https://www.e-solat.gov.my/index.php?siteId=24&pageId=50
sensor:
  ## Time Sensors ##
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'
  - platform: template
    sensors:
        time_formatted:
            friendly_name: "Date and time"
            value_template: "{{ as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%A, %-d %B %Y - %I:%M %p') }}"
            icon_template: mdi:calendar-clock
        time_12hours:
            friendly_name: "Time"
            value_template: "{{ as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%I:%M %p') }}"
            icon_template: mdi:clock
  
  ## Waktu Solat (JAKIM) ##
  - platform: rest
    resource: https://www.e-solat.gov.my/index.php?r=esolatApi/takwimsolat&period=today&zone=SGR01
    name: Jakim Official
    json_attributes:
      - zone
      - prayerTime
      - serverTime
    value_template: '{{ value_json.zone }}'
  - platform: template
    sensors:
        jakim_hijri:
            friendly_name: "Hijri Date"
            icon_template: mdi:calendar
            value_template: '{{states.sensor.jakim_official.attributes.prayerTime[0].hijri}}'
        jakim_hijri_full:
            friendly_name: "Hijri Date Full"
            icon_template: mdi:calendar
            value_template: >
              {% set months = ['Muharram', 'Safar', 'Rabi\'ul Awwal', 'Rabi\'ul Akhir', 'Jamadil Awwal', 'Jamadil Akhir', 'Rejab', 'Sha\'aban', 'Ramadhan', 'Syawwal', 'Zulkaedah', 'Zulhijjah'] %}
              {{states.sensor.jakim_official.attributes.prayerTime[0].hijri[8:10]}} {{months[(states.sensor.jakim_official.attributes.prayerTime[0].hijri[5:7] | int)-1]}} {{states.sensor.jakim_official.attributes.prayerTime[0].hijri[0:4]}}h
        esolat_imsak:
            friendly_name: "Imsak"
            icon_template: mdi:islam
            value_template: '{{as_timestamp(strptime(states.sensor.jakim_official.attributes.prayerTime[0].imsak, "%H:%M:%S")) | timestamp_custom("%I:%M %p", true)}}'
            attribute_templates: 
                24hours: '{{as_timestamp(strptime(states.sensor.jakim_official.attributes.prayerTime[0].imsak, "%H:%M:%S")) | timestamp_custom("%H:%M", true)}}'
        esolat_subuh:
            friendly_name: "Subuh"
            icon_template: mdi:islam
            value_template: '{{as_timestamp(strptime(states.sensor.jakim_official.attributes.prayerTime[0].fajr, "%H:%M:%S")) | timestamp_custom("%I:%M %p", true)}}'
            attribute_templates: 
                24hours: '{{as_timestamp(strptime(states.sensor.jakim_official.attributes.prayerTime[0].fajr, "%H:%M:%S")) | timestamp_custom("%H:%M", true)}}'
        esolat_syuruk:
            friendly_name: "Syuruk"
            icon_template: mdi:islam
            value_template: '{{as_timestamp(strptime(states.sensor.jakim_official.attributes.prayerTime[0].syuruk, "%H:%M:%S")) | timestamp_custom("%I:%M %p", true)}}'
            attribute_templates: 
                24hours: '{{as_timestamp(strptime(states.sensor.jakim_official.attributes.prayerTime[0].syuruk, "%H:%M:%S")) | timestamp_custom("%H:%M", true)}}'
        esolat_zohor:
            friendly_name: "Zohor"
            icon_template: mdi:islam
            value_template: '{{as_timestamp(strptime(states.sensor.jakim_official.attributes.prayerTime[0].dhuhr, "%H:%M:%S")) | timestamp_custom("%I:%M %p", true)}}'
            attribute_templates: 
                24hours: '{{as_timestamp(strptime(states.sensor.jakim_official.attributes.prayerTime[0].dhuhr, "%H:%M:%S")) | timestamp_custom("%H:%M", true)}}'
        esolat_asar:
            friendly_name: "Asar"
            icon_template: mdi:islam
            value_template: '{{as_timestamp(strptime(states.sensor.jakim_official.attributes.prayerTime[0].asr, "%H:%M:%S")) | timestamp_custom("%I:%M %p", true)}}'
            attribute_templates: 
                24hours: '{{as_timestamp(strptime(states.sensor.jakim_official.attributes.prayerTime[0].asr, "%H:%M:%S")) | timestamp_custom("%H:%M", true)}}'
        esolat_maghrib:
            friendly_name: "Maghrib"
            icon_template: mdi:islam
            value_template: '{{as_timestamp(strptime(states.sensor.jakim_official.attributes.prayerTime[0].maghrib, "%H:%M:%S")) | timestamp_custom("%I:%M %p", true)}}'
            attribute_templates: 
                24hours: '{{as_timestamp(strptime(states.sensor.jakim_official.attributes.prayerTime[0].maghrib, "%H:%M:%S")) | timestamp_custom("%H:%M", true)}}'
        esolat_isyak:
            friendly_name: "Isyak"
            icon_template: mdi:islam
            value_template: '{{as_timestamp(strptime(states.sensor.jakim_official.attributes.prayerTime[0].isha, "%H:%M:%S")) | timestamp_custom("%I:%M %p", true)}}'
            attribute_templates: 
                24hours: '{{as_timestamp(strptime(states.sensor.jakim_official.attributes.prayerTime[0].isha, "%H:%M:%S")) | timestamp_custom("%H:%M", true)}}'
        esolat_waktusekarang:
            friendly_name: "Waktu Sekarang"
            icon_template: mdi:islam
            value_template: >-
                {% if states("sensor.time") >= state_attr("sensor.esolat_imsak", "24hours") and states("sensor.time") < state_attr("sensor.esolat_subuh", "24hours") %}
                Imsak
                {% elif states("sensor.time") >= state_attr("sensor.esolat_subuh", "24hours") and states("sensor.time") < state_attr("sensor.esolat_syuruk", "24hours") %}
                Subuh
                {% elif states("sensor.time") >= state_attr("sensor.esolat_syuruk", "24hours") and states("sensor.time") < state_attr("sensor.esolat_zohor", "24hours") %}
                Syuruk
                {% elif states("sensor.time") >= state_attr("sensor.esolat_zohor", "24hours") and states("sensor.time") < state_attr("sensor.esolat_asar", "24hours") %}
                Zohor
                {% elif states("sensor.time") >= state_attr("sensor.esolat_asar", "24hours") and states("sensor.time") < state_attr("sensor.esolat_maghrib", "24hours") %}
                Asar
                {% elif states("sensor.time") >= state_attr("sensor.esolat_maghrib", "24hours") and states("sensor.time") < state_attr("sensor.esolat_isyak", "24hours") %}
                Maghrib
                {% elif states("sensor.time") >= state_attr("sensor.esolat_isyak", "24hours") %}
                Isyak
                {%- else %}
                Isyak
                {%- endif %}
