## Malaysia prayer time based on JAKIM Official API
## Version 3.0 - Location and source can be selected from input_select and input_text. 

## Hijri Date API ##
- platform: rest
  resource_template: "http://api.aladhan.com/v1/gToH?date={{ now().strftime('%d-%m-%Y') }}"
  name: HijriDate API
  json_attributes_path: "$.data.hijri"
  json_attributes:
    - day
    - month
    - year
    - holiday
  value_template: "{{ value_json.data.hijri.date }}"
  
- platform: template
  sensors:
    hijridate:
      friendly_name: "Hijri Date"
      icon_template: mdi:calendar
      value_template: >-
        {% set months = ["Muharram", "Safar", "Rabi\'ul Awwal", "Rabi\'ul Akhir", "Jamadil Awwal", "Jamadil Akhir", "Rejab", "Sha\'aban", "Ramadhan", "Syawal", "Zulkaedah", "Zulhijjah"] %}
        {{ state_attr("sensor.hijridate_api", "day") + " " + months[state_attr("sensor.hijridate_api", "month").number] + " " + state_attr("sensor.hijridate_api", "year") + "h" }}

## Solat API ##
- platform: rest
  name: solat_local
  resource_template: "{{states('input_text.homeurl')}}/local/esolat.json"
  #resource: https://xxxx.duckdns.org/local/esolat.json # Domain name
  #resource: http://192.168.0.123:8123/local/esolat.json # IP address
  json_attributes:
    - zone
    - prayerTime
    - serverTime
  value_template: '{{ value_json.zone }}'
- platform: rest
  name: solat_azanpro
  scan_interval: 7200
  resource_template: "https://api.azanpro.com/times/today.json?zone={{states('input_text.solat')}}&format=24-hour"
  json_attributes:
    - zone
    - prayer_times
  value_template: >-
    {% if value_json is defined %}{{ value_json.zone }}
    {% else %}Offline
    {% endif %}
- platform: rest
  name: solat_jakim
  scan_interval: 7200
  resource_template: "https://www.e-solat.gov.my/index.php?r=esolatApi/takwimsolat&period=today&zone={{states('input_text.solat')}}"
  json_attributes:
    - zone
    - prayerTime
  value_template: >-
    {% if value_json is defined %}{{ value_json.zone }}
    {% else %}Offline
    {% endif %}
- platform: template
  sensors:
    solat_imsak:
      friendly_name: "Imsak"
      icon_template: mdi:star-crescent
      value_template: >-
        {%if is_state("input_select.solat", "eSolat")%}{{as_timestamp(now().date() ~ " " ~ state_attr('sensor.solat_jakim', 'prayerTime')[0].imsak) | timestamp_custom("%I:%M %p", true)}}
        {%elif is_state("input_select.solat", "AzanPro")%}{%if as_timestamp(now().date() ~ " " ~ state_attr("sensor.solat_azanpro", "prayer_times")["imsak"], "%H:%M") | timestamp_custom("%I:%M %p", true) == "%H:%M"%}Unavailable{%else%}{{as_timestamp(now().date() ~ " " ~ state_attr("sensor.solat_azanpro", "prayer_times")["imsak"], "%H:%M") | timestamp_custom("%I:%M %p", true)}}{%endif%}
        {%elif is_state("input_select.solat", "Local")%}{%set yearday = now().strftime("%j") | int%}{{as_timestamp(strptime(state_attr("sensor.solat_local", "prayerTime")[yearday-1].imsak, "%H:%M:%S")) | timestamp_custom("%I:%M %p", true)}}
        {%endif%}
      attribute_templates: 
        24hours: >-
          {%if is_state("input_select.solat", "eSolat")%}{{strptime(state_attr('sensor.solat_jakim', 'prayerTime')[0].imsak[0:5],'%I:%M %p')}}
          {%elif is_state("input_select.solat", "AzanPro")%}{{state_attr("sensor.solat_azanpro", "prayer_times")["imsak"]}}
          {%elif is_state("input_select.solat", "Local")%}{%set yearday = now().strftime("%j") | int%}{{as_timestamp(strptime(state_attr("sensor.solat_local", "prayerTime")[yearday-1].imsak, "%H:%M:%S")) | timestamp_custom("%H:%M", true)}}
          {%endif%}
        source: >-
          {%if is_state("input_select.solat", "eSolat")%}eSolat
          {%elif is_state("input_select.solat", "AzanPro")%}AzanPro
          {%elif is_state("input_select.solat", "Local")%}Local
          {%endif%}
    solat_subuh:
      friendly_name: "Subuh"
      icon_template: mdi:star-crescent
      value_template: >-
        {%if is_state("input_select.solat", "eSolat")%}{{as_timestamp(now().date() ~ " " ~ state_attr('sensor.solat_jakim', 'prayerTime')[0].fajr) | timestamp_custom("%I:%M %p", true)}}
        {%elif is_state("input_select.solat", "AzanPro")%}{%if as_timestamp(now().date() ~ " " ~ state_attr("sensor.solat_azanpro", "prayer_times")["subuh"], "%H:%M") | timestamp_custom("%I:%M %p", true) == "%H:%M"%}Unavailable{%else%}{{as_timestamp(now().date() ~ " " ~ state_attr("sensor.solat_azanpro", "prayer_times")["subuh"], "%H:%M") | timestamp_custom("%I:%M %p", true)}}{%endif%}
        {%elif is_state("input_select.solat", "Local")%}{%set yearday = now().strftime("%j") | int%}{{as_timestamp(strptime(state_attr("sensor.solat_local", "prayerTime")[yearday-1].fajr, "%H:%M:%S")) | timestamp_custom("%I:%M %p", true)}}
        {%endif%}
      attribute_templates: 
        24hours: >-
          {%if is_state("input_select.solat", "eSolat")%}{{strptime(state_attr('sensor.solat_jakim', 'prayerTime')[0].fajr[0:5],'%I:%M %p')}}
          {%elif is_state("input_select.solat", "AzanPro")%}{{state_attr("sensor.solat_azanpro", "prayer_times")["subuh"]}}
          {%elif is_state("input_select.solat", "Local")%}{%set yearday = now().strftime("%j") | int%}{{as_timestamp(strptime(state_attr("sensor.solat_local", "prayerTime")[yearday-1].fajr, "%H:%M:%S")) | timestamp_custom("%H:%M", true)}}
          {%endif%}
        source: >-
          {%if is_state("input_select.solat", "eSolat")%}eSolat
          {%elif is_state("input_select.solat", "AzanPro")%}AzanPro
          {%elif is_state("input_select.solat", "Local")%}Local
          {%endif%}
    solat_syuruk:
      friendly_name: "Syuruk"
      icon_template: mdi:star-crescent
      value_template: >-
        {%if is_state("input_select.solat", "eSolat")%}{{as_timestamp(now().date() ~ " " ~ state_attr('sensor.solat_jakim', 'prayerTime')[0].syuruk) | timestamp_custom("%I:%M %p", true)}}
        {%elif is_state("input_select.solat", "AzanPro")%}{%if as_timestamp(now().date() ~ " " ~ state_attr("sensor.solat_azanpro", "prayer_times")["syuruk"], "%H:%M") | timestamp_custom("%I:%M %p", true) == "%H:%M"%}Unavailable{%else%}{{as_timestamp(now().date() ~ " " ~ state_attr("sensor.solat_azanpro", "prayer_times")["syuruk"], "%H:%M") | timestamp_custom("%I:%M %p", true)}}{%endif%}
        {%elif is_state("input_select.solat", "Local")%}{%set yearday = now().strftime("%j") | int%}{{as_timestamp(strptime(state_attr("sensor.solat_local", "prayerTime")[yearday-1].syuruk, "%H:%M:%S")) | timestamp_custom("%I:%M %p", true)}}
        {%endif%}
      attribute_templates: 
        24hours: >-
          {%if is_state("input_select.solat", "eSolat")%}{{strptime(state_attr('sensor.solat_jakim', 'prayerTime')[0].syuruk[0:5],'%I:%M %p')}}
          {%elif is_state("input_select.solat", "AzanPro")%}{{state_attr("sensor.solat_azanpro", "prayer_times")["syuruk"]}}
          {%elif is_state("input_select.solat", "Local")%}{%set yearday = now().strftime("%j") | int%}{{as_timestamp(strptime(state_attr("sensor.solat_local", "prayerTime")[yearday-1].syuruk, "%H:%M:%S")) | timestamp_custom("%H:%M", true)}}
          {%endif%}
        source: >-
          {%if is_state("input_select.solat", "eSolat")%}eSolat
          {%elif is_state("input_select.solat", "AzanPro")%}AzanPro
          {%elif is_state("input_select.solat", "Local")%}Local
          {%endif%}
    solat_zohor:
      friendly_name: "Zohor"
      icon_template: mdi:star-crescent
      value_template: >-
        {%if is_state("input_select.solat", "eSolat")%}{{as_timestamp(now().date() ~ " " ~ state_attr('sensor.solat_jakim', 'prayerTime')[0].dhuhr) | timestamp_custom("%I:%M %p", true)}}
        {%elif is_state("input_select.solat", "AzanPro")%}{%if as_timestamp(now().date() ~ " " ~ state_attr("sensor.solat_azanpro", "prayer_times")["zohor"], "%H:%M") | timestamp_custom("%I:%M %p", true) == "%H:%M"%}Unavailable{%else%}{{as_timestamp(now().date() ~ " " ~ state_attr("sensor.solat_azanpro", "prayer_times")["zohor"], "%H:%M") | timestamp_custom("%I:%M %p", true)}}{%endif%}
        {%elif is_state("input_select.solat", "Local")%}{%set yearday = now().strftime("%j") | int%}{{as_timestamp(strptime(state_attr("sensor.solat_local", "prayerTime")[yearday-1].dhuhr, "%H:%M:%S")) | timestamp_custom("%I:%M %p", true)}}
        {%endif%}
      attribute_templates: 
        24hours: >-
          {%if is_state("input_select.solat", "eSolat")%}{{strptime(state_attr('sensor.solat_jakim', 'prayerTime')[0].dhuhr[0:5],'%I:%M %p')}}
          {%elif is_state("input_select.solat", "AzanPro")%}{{state_attr("sensor.solat_azanpro", "prayer_times")["zohor"]}}
          {%elif is_state("input_select.solat", "Local")%}{%set yearday = now().strftime("%j") | int%}{{as_timestamp(strptime(state_attr("sensor.solat_local", "prayerTime")[yearday-1].dhuhr, "%H:%M:%S")) | timestamp_custom("%H:%M", true)}}
          {%endif%}
        source: >-
          {%if is_state("input_select.solat", "eSolat")%}eSolat
          {%elif is_state("input_select.solat", "AzanPro")%}AzanPro
          {%elif is_state("input_select.solat", "Local")%}Local
          {%endif%}
    solat_asar:
      friendly_name: "Asar"
      icon_template: mdi:star-crescent
      value_template: >-
        {%if is_state("input_select.solat", "eSolat")%}{{as_timestamp(now().date() ~ " " ~ state_attr('sensor.solat_jakim', 'prayerTime')[0].asr) | timestamp_custom("%I:%M %p", true)}}
        {%elif is_state("input_select.solat", "AzanPro")%}{%if as_timestamp(now().date() ~ " " ~ state_attr("sensor.solat_azanpro", "prayer_times")["asar"], "%H:%M") | timestamp_custom("%I:%M %p", true) == "%H:%M"%}Unavailable{%else%}{{as_timestamp(now().date() ~ " " ~ state_attr("sensor.solat_azanpro", "prayer_times")["asar"], "%H:%M") | timestamp_custom("%I:%M %p", true)}}{%endif%}
        {%elif is_state("input_select.solat", "Local")%}{%set yearday = now().strftime("%j") | int%}{{as_timestamp(strptime(state_attr("sensor.solat_local", "prayerTime")[yearday-1].asr, "%H:%M:%S")) | timestamp_custom("%I:%M %p", true)}}
        {%endif%}
      attribute_templates: 
        24hours: >-
          {%if is_state("input_select.solat", "eSolat")%}{{strptime(state_attr('sensor.solat_jakim', 'prayerTime')[0].asr[0:5],'%I:%M %p')}}
          {%elif is_state("input_select.solat", "AzanPro")%}{{state_attr("sensor.solat_azanpro", "prayer_times")["asar"]}}
          {%elif is_state("input_select.solat", "Local")%}{%set yearday = now().strftime("%j") | int%}{{as_timestamp(strptime(state_attr("sensor.solat_local", "prayerTime")[yearday-1].asr, "%H:%M:%S")) | timestamp_custom("%H:%M", true)}}
          {%endif%}
        source: >-
          {%if is_state("input_select.solat", "eSolat")%}eSolat
          {%elif is_state("input_select.solat", "AzanPro")%}AzanPro
          {%elif is_state("input_select.solat", "Local")%}Local
          {%endif%}
    solat_maghrib:
      friendly_name: "Maghrib"
      icon_template: mdi:star-crescent
      value_template: >-
        {%if is_state("input_select.solat", "eSolat")%}{{as_timestamp(now().date() ~ " " ~ state_attr('sensor.solat_jakim', 'prayerTime')[0].maghrib) | timestamp_custom("%I:%M %p", true)}}
        {%elif is_state("input_select.solat", "AzanPro")%}{%if as_timestamp(now().date() ~ " " ~ state_attr("sensor.solat_azanpro", "prayer_times")["maghrib"], "%H:%M") | timestamp_custom("%I:%M %p", true) == "%H:%M"%}Unavailable{%else%}{{as_timestamp(now().date() ~ " " ~ state_attr("sensor.solat_azanpro", "prayer_times")["maghrib"], "%H:%M") | timestamp_custom("%I:%M %p", true)}}{%endif%}
        {%elif is_state("input_select.solat", "Local")%}{%set yearday = now().strftime("%j") | int%}{{as_timestamp(strptime(state_attr("sensor.solat_local", "prayerTime")[yearday-1].maghrib, "%H:%M:%S")) | timestamp_custom("%I:%M %p", true)}}
        {%endif%}
      attribute_templates: 
        24hours: >-
          {%if is_state("input_select.solat", "eSolat")%}{{strptime(state_attr('sensor.solat_jakim', 'prayerTime')[0].maghrib[0:5],'%I:%M %p')}}
          {%elif is_state("input_select.solat", "AzanPro")%}{{state_attr("sensor.solat_azanpro", "prayer_times")["maghrib"]}}
          {%elif is_state("input_select.solat", "Local")%}{%set yearday = now().strftime("%j") | int%}{{as_timestamp(strptime(state_attr("sensor.solat_local", "prayerTime")[yearday-1].maghrib, "%H:%M:%S")) | timestamp_custom("%H:%M", true)}}
          {%endif%}
        source: >-
          {%if is_state("input_select.solat", "eSolat")%}eSolat
          {%elif is_state("input_select.solat", "AzanPro")%}AzanPro
          {%elif is_state("input_select.solat", "Local")%}Local
          {%endif%}
    solat_isyak:
      friendly_name: "Isyak"
      icon_template: mdi:star-crescent
      value_template: >-
        {%if is_state("input_select.solat", "eSolat")%}{{as_timestamp(now().date() ~ " " ~ state_attr('sensor.solat_jakim', 'prayerTime')[0].isha) | timestamp_custom("%I:%M %p", true)}}
        {%elif is_state("input_select.solat", "AzanPro")%}{%if as_timestamp(now().date() ~ " " ~ state_attr("sensor.solat_azanpro", "prayer_times")["isyak"], "%H:%M") | timestamp_custom("%I:%M %p", true) == "%H:%M"%}Unavailable{%else%}{{as_timestamp(now().date() ~ " " ~ state_attr("sensor.solat_azanpro", "prayer_times")["isyak"], "%H:%M") | timestamp_custom("%I:%M %p", true)}}{%endif%}
        {%elif is_state("input_select.solat", "Local")%}{%set yearday = now().strftime("%j") | int%}{{as_timestamp(strptime(state_attr("sensor.solat_local", "prayerTime")[yearday-1].isha, "%H:%M:%S")) | timestamp_custom("%I:%M %p", true)}}
        {%endif%}
      attribute_templates: 
        24hours: >-
          {%if is_state("input_select.solat", "eSolat")%}{{strptime(state_attr('sensor.solat_jakim', 'prayerTime')[0].isha[0:5],'%I:%M %p')}}
          {%elif is_state("input_select.solat", "AzanPro")%}{{state_attr("sensor.solat_azanpro", "prayer_times")["isyak"]}}
          {%elif is_state("input_select.solat", "Local")%}{%set yearday = now().strftime("%j") | int%}{{as_timestamp(strptime(state_attr("sensor.solat_local", "prayerTime")[yearday-1].isha, "%H:%M:%S")) | timestamp_custom("%H:%M", true)}}
          {%endif%}
        source: >-
          {%if is_state("input_select.solat", "eSolat")%}eSolat
          {%elif is_state("input_select.solat", "AzanPro")%}AzanPro
          {%elif is_state("input_select.solat", "Local")%}Local
          {%endif%}
    solat_sekarang:
      friendly_name: "Waktu Sekarang"
      icon_template: mdi:star-crescent
      value_template: >-
        {%if now().strftime("%H:%M") >= state_attr("sensor.solat_imsak", "24hours") and now().strftime("%H:%M") < state_attr("sensor.solat_subuh", "24hours")%}Imsak
        {%elif now().strftime("%H:%M") >= state_attr("sensor.solat_subuh", "24hours") and now().strftime("%H:%M") < state_attr("sensor.solat_syuruk", "24hours")%}Subuh
        {%elif now().strftime("%H:%M") >= state_attr("sensor.solat_syuruk", "24hours") and now().strftime("%H:%M") < state_attr("sensor.solat_zohor", "24hours")%}Syuruk
        {%elif now().strftime("%H:%M") >= state_attr("sensor.solat_zohor", "24hours") and now().strftime("%H:%M") < state_attr("sensor.solat_asar", "24hours")%}Zohor
        {%elif now().strftime("%H:%M") >= state_attr("sensor.solat_asar", "24hours") and now().strftime("%H:%M") < state_attr("sensor.solat_maghrib", "24hours")%}Asar
        {%elif now().strftime("%H:%M") >= state_attr("sensor.solat_maghrib", "24hours") and now().strftime("%H:%M") < state_attr("sensor.solat_isyak", "24hours")%}Maghrib
        {%elif now().strftime("%H:%M") >= state_attr("sensor.solat_isyak", "24hours")%}Isyak
        {%else%}Isyak
        {%endif%}
      attribute_templates:
        24hours: >-
          {%if now().strftime("%H:%M") >= state_attr("sensor.solat_imsak", "24hours") and now().strftime("%H:%M") < state_attr("sensor.solat_subuh", "24hours")%}{{state_attr("sensor.solat_imsak", "24hours")}}
          {%elif now().strftime("%H:%M") >= state_attr("sensor.solat_subuh", "24hours") and now().strftime("%H:%M") < state_attr("sensor.solat_syuruk", "24hours")%}{{state_attr("sensor.solat_subuh", "24hours")}}
          {%elif now().strftime("%H:%M") >= state_attr("sensor.solat_syuruk", "24hours") and now().strftime("%H:%M") < state_attr("sensor.solat_zohor", "24hours")%}{{state_attr("sensor.solat_syuruk", "24hours")}}
          {%elif now().strftime("%H:%M") >= state_attr("sensor.solat_zohor", "24hours") and now().strftime("%H:%M") < state_attr("sensor.solat_asar", "24hours")%}{{state_attr("sensor.solat_zohor", "24hours")}}
          {%elif now().strftime("%H:%M") >= state_attr("sensor.solat_asar", "24hours") and now().strftime("%H:%M") < state_attr("sensor.solat_maghrib", "24hours")%}{{state_attr("sensor.solat_asar", "24hours")}}
          {%elif now().strftime("%H:%M") >= state_attr("sensor.solat_maghrib", "24hours") and now().strftime("%H:%M") < state_attr("sensor.solat_isyak", "24hours")%}{{state_attr("sensor.solat_maghrib", "24hours")}}
          {%elif now().strftime("%H:%M") >= state_attr("sensor.solat_isyak", "24hours")%}{{state_attr("sensor.solat_isyak", "24hours")}}
          {%else%}{{state_attr("sensor.solat_isyak", "24hours")}}
          {%endif%}
        source: >-
          {%if is_state("input_select.solat", "eSolat")%}eSolat
          {%elif is_state("input_select.solat", "AzanPro")%}AzanPro
          {%elif is_state("input_select.solat", "Local")%}Local
          {%endif%}
